fix(use-i18n)!: move date-fns dynamic import outside of library scope
scaleway/scaleway-lib pull request #145
Opened 2021-04-29 15:25 UTC by chambo-e

This was causing a SIGSEGV for some reason on our tests

BREAKING CHANGE: We now expose loadDateLocale props in the Provider instead of bundling it

2021-04-29 15:33 UTC, philibea requested changes

2021-04-29 15:33 UTC, philibea commented on packages/use-i18n/README.md
> +const load = ({ locale, namespace }) => import(`./locales/${locale}/${namespace}`)
const load = async ({ locale, namespace }) => import(`./locales/${locale}/${namespace}`)

2021-04-29 15:33 UTC, philibea commented on packages/use-i18n/README.md
> +const loadDateLocale = (locale) => import(`date-fns/locale/${locale}/index`)
const loadDateLocale = async (locale) => import(`date-fns/locale/${locale}/index`)

2021-04-30 06:51 UTC, matthprost approved these changes

2021-04-30 07:26 UTC, philibea approved these changes

2021-04-30 07:33 UTC, merged