docs(readme): fixup links and bundlephobias
scaleway/scaleway-lib pull request #1599
Opened 2023-10-23 11:40 UTC by Slashgear

## Why

Some links are broken in the global readme of the repository
- bundlephobia pages are not working because package does not export entrypoints
- they are broken links in growthbook package

## How

- fix global readme links
- re-add main entry to make bundlephobia working

@QuiiBz What is your opinion on re-adding main key on package ?

2023-10-23 13:35 UTC, QuiiBz requested changes
We shouldn't (and don't) need the `main` field in each `package.json`, since we're using the "new" `exports` field instead which covers all our needs.

It's probably a bug (or at least an unsupported feature) of bundlephobia to not support the `exports` field - example with packagephobia, which supports it fine: https://packagephobia.com/result?p=%40scaleway%2Fjest-helpers

2023-10-23 15:11 UTC, Slashgear commented
Ok I will change that

2023-10-23 15:26 UTC, QuiiBz approved these changes

2023-10-23 15:26 UTC, QuiiBz commented on .changeset/rotten-beans-juggle.md
We should probably remove the changeset since no packages are impacted.

2023-10-24 08:31 UTC, ModuloM approved these changes

2023-10-24 09:11 UTC, merged