feat: concurrent request handle with dataloader
scaleway/scaleway-lib pull request #392
Opened 2021-09-21 12:28 UTC by DorianMaliszewski

Handle when there multiple same request to avoid multiple same promise resolution.

2021-09-21 13:24 UTC, matthprost requested changes

2021-09-21 13:24 UTC, matthprost commented on packages/use-dataloader/src/DataLoaderProvider.tsx
>      },
```suggestion
      if (!key || typeof key !== 'string') throw new Error('Key should exist and be a string')
        const notifyChanges = (updatedRequest: DataLoader) => {
          setRequestQueue(current => ({
            ...current,
            [computeKey(updatedRequest.key)]: updatedRequest,
          }))
        }
        const newRequest = new DataLoader({ ...args, notify: notifyChanges })
        newRequest.addOnSuccessListener(result => {
          if (result !== undefined && result !== null)
            addCachedData(key, result)
        })
        setRequestQueue(current => ({
          ...current,
          [computeKey(key)]: newRequest,
        }))

        addReload(key, newRequest.launch)

        return newRequest
      }
```

2021-09-21 13:24 UTC, matthprost commented on packages/use-dataloader/src/DataLoaderProvider.tsx
> +  )
```suggestion
  const reload = useCallback(
    async (key?: string) => {
      if (!key || typeof key !== 'string') throw new Error('Key should exist and be a string')
      await (reloads.current[computeKey(key)] && reloads.current[computeKey(key)]())
    },
    [computeKey],
  )
```

2021-09-21 13:24 UTC, matthprost commented on packages/use-dataloader/src/DataLoaderProvider.tsx
> +      }
To put a throw error on every function if key is not string or it doesn't exists

2021-09-21 13:39 UTC, matthprost requested changes

2021-09-21 13:39 UTC, matthprost commented on packages/use-dataloader/src/dataloader.ts
> +      }
```suggestion
      if (this.errorListeners?.length > 0) {
        this.errorListeners.forEach(
          listener => void listener?.(this.error as Error),
        )
      }
```

2021-09-21 13:39 UTC, matthprost commented on packages/use-dataloader/src/dataloader.ts
> +    }
```suggestion
    if (this.cancelListeners.length > 0) {
      this.cancelListeners.forEach(listener => void listener?.())
    }
```

2021-09-22 14:05 UTC, matthprost requested changes

2021-09-22 14:29 UTC, matthprost requested changes

2021-09-22 14:29 UTC, matthprost commented on packages/use-dataloader/src/DataLoaderProvider.tsx
> +          reloads.current[computeKey(key)]())
```suggestion
        await (reloads.current[computeKey(key)]?.())
```

2021-09-22 14:29 UTC, matthprost commented on packages/use-dataloader/src/__tests__/useDataLoader.test.tsx
> +    expect(result.error?.message).toBe('Key should be a string')
Here you can probably import `KEY_IS_NOT_STRING_ERROR` constant and check trough it

2021-09-23 08:36 UTC, matthprost approved these changes

2021-09-27 09:48 UTC, adriengibrat requested changes

2021-09-27 09:48 UTC, adriengibrat commented on packages/use-dataloader/src/constants.ts
> +> = {
Why not using actal enum ;)
```suggestion
export enum StatusEnum {
```

then replace all `DataLoaderStatus` with the enum type

2021-09-27 09:48 UTC, DorianMaliszewski commented on packages/use-dataloader/src/DataLoaderProvider.tsx
> +      } else throw new Error(KEY_IS_NOT_STRING_ERROR)
No like this we ensure user use this lib according to our expectation. This allow us to omit string verification or others and focus on quality

2021-09-27 09:49 UTC, DorianMaliszewski commented on packages/use-dataloader/src/__tests__/DataLoaderProvider.test.tsx
> +/* eslint-disable @typescript-eslint/ban-ts-comment */
Because i tried to pass some integers to make sure errors are throw and ensure all is working

2021-09-27 09:50 UTC, DorianMaliszewski commented on packages/use-dataloader/src/dataloader.ts
> +/* eslint-disable no-void */
I can't launch the void promise like we did in useDataloader before if I don't put this 😢

2021-09-27 12:46 UTC, vincentaudebert approved these changes

2021-09-27 13:00 UTC, merged