feat: refresh data on max lifetime reached
scaleway/scaleway-lib pull request #399
Opened 2021-09-27 14:03 UTC by DorianMaliszewski

Consider data as outdated when maxLifetime is reached. Allow stalled data detection when there are multiple useDataLoader with same key. (Performance)

2021-09-27 15:03 UTC, matthprost requested changes

2021-09-27 15:03 UTC, matthprost commented on packages/use-dataloader/src/DataLoaderProvider.tsx
> +  maxDataLifetime?: number
Can we add it into documentation with a precision that this value is in milliseconds ?

2021-09-27 15:16 UTC, matthprost requested changes

2021-09-27 15:16 UTC, matthprost commented on packages/use-dataloader/README.md
> +    maxDataLifetime, // Max time before preivous success data is outdated
```suggestion
    maxDataLifetime, // Max time before previous success data is outdated (in milliseconds)
```

2021-09-27 15:16 UTC, matthprost commented on packages/use-dataloader/src/DataLoaderProvider.tsx
> +   * Max time before data from previous success is considered as outdated
```suggestion
   * Max time before data from previous success is considered as outdated (in milliseconds)
```

2021-09-27 15:16 UTC, matthprost commented on packages/use-dataloader/src/types.ts
> +   * Max time before data from previous success is considered as outdated
```suggestion
   * Max time before data from previous success is considered as outdated (in milliseconds)
```

2021-09-27 16:21 UTC, adriengibrat approved these changes

2021-09-28 07:58 UTC, chambo-e approved these changes

2021-09-28 09:21 UTC, matthprost approved these changes

2021-09-28 09:22 UTC, merged