feat: add mac address regex
scaleway/scaleway-lib pull request #67
Opened 2021-03-08 13:48 UTC by DorianMaliszewski

# What's done ?

- Only add macAddress regex

2021-03-08 13:49 UTC, chambo-e requested changes

2021-03-08 13:49 UTC, chambo-e commented on packages/regex/src/index.js
> +export const macAddress = /^([0-9a-fA-F][0-9a-fA-F]:){5}([0-9a-fA-F][0-9a-fA-F])$/
On teeny-tiny test pls :)

2021-03-08 14:03 UTC, chambo-e approved these changes

2021-03-09 09:09 UTC, vincentaudebert approved these changes

2021-03-12 11:36 UTC, merged