refactor: allow uppercase in basic domain - regex
scaleway/scaleway-lib pull request #994
Opened 2022-09-22 14:54 UTC by Lawndlwd

2022-09-22 15:21 UTC, matthprost requested changes

2022-09-22 15:21 UTC, matthprost commented on packages/regex/src/index.ts
> +export const basicDomain = /^[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]{1,63})+$/
Please make another regex for allowing uppercase

2022-09-23 11:54 UTC, baptisteArno approved these changes

2022-09-23 11:54 UTC, baptisteArno commented on packages/regex/src/index.ts
> +export const basicDomainNotStrict =
I think `notStrict` isn't declarative enough

Why not calling it `uppercaseBasicDomain`?

2022-09-23 12:15 UTC, matthprost approved these changes

2022-09-23 12:26 UTC, merged